---
apiVersion: v1
kind: Pod
metadata:
  name: app-secret
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/foo
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: simple-secret
