apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: app-job-rsync
        image: google/cloud-sdk:275.0.0-alpine
        command: ["/bin/sh", "-c"]
        args:
        - "gsutil -m rsync -dr gs://glow-sportradar/ /data/input"
        volumeMounts:
        - name: data-disk
          mountPath: /data/input
      restartPolicy: Never
      volumes:
      - name: data-disk
        gcePersistentDisk:
          pdName: glow-data-disk-200
          fsType: ext4
